#!/usr/bin/env bash
# ============================================================
#  Webuzo Nginx Fix — Diagnose and patch the correct vhost
# ============================================================
#  Usage:
#    bash fix-nginx.sh globalexperiencegh.org
# ============================================================

set -e

DOMAIN="${1:-}"
if [ -z "$DOMAIN" ]; then
  echo "Usage: bash fix-nginx.sh your-domain.com"
  exit 1
fi

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'
print_step() { echo -e "\n${BLUE}==>${NC} $1"; }
print_ok()   { echo -e "${GREEN}✓${NC} $1"; }
print_warn() { echo -e "${YELLOW}⚠${NC} $1"; }
print_err()  { echo -e "${RED}✗${NC} $1"; }

# --- 1. Verify Node app is running on port 3000 ----------------------------
print_step "Checking if Node app is running on port 3000"
if curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:3000/ | grep -q "200\|302"; then
  print_ok "Node app is responding on port 3000"
else
  print_err "Node app is NOT responding on port 3000!"
  echo "  Run: pm2 status"
  echo "  If not running: cd ~/global-experience && bash deploy.sh"
  echo ""
  echo "  Trying anyway in case it's just slow to respond..."
fi

# --- 2. Find all Nginx config directories -----------------------------------
print_step "Finding Nginx configuration directories"
NGINX_DIRS=()
for d in \
  /etc/nginx/conf.d \
  /etc/nginx/sites-available \
  /usr/local/apps/nginx/etc/conf.d \
  /usr/local/apps/nginx/etc/vhosts \
  /etc/nginx/vhost.d \
  /etc/nginx/sites-enabled; do
  if [ -d "$d" ]; then
    NGINX_DIRS+=("$d")
    print_ok "Found: $d"
  fi
done

if [ ${#NGINX_DIRS[@]} -eq 0 ]; then
  print_err "No Nginx config directories found! Is Nginx installed?"
  exit 1
fi

# --- 3. Find the vhost config for this domain -------------------------------
print_step "Searching for existing vhost config for $DOMAIN"

DOMAIN_CONF=""
for d in "${NGINX_DIRS[@]}"; do
  for f in "$d/$DOMAIN" "$d/$DOMAIN.conf" "$d/${DOMAIN}.conf"; do
    if [ -f "$f" ]; then
      DOMAIN_CONF="$f"
      break 2
    fi
  done
  # Also search for any file containing the domain name
  if [ -z "$DOMAIN_CONF" ]; then
    FOUND=$(grep -rl "server_name.*$DOMAIN" "$d" 2>/dev/null | head -1)
    if [ -n "$FOUND" ]; then
      DOMAIN_CONF="$FOUND"
      break
    fi
  fi
done

if [ -n "$DOMAIN_CONF" ]; then
  print_ok "Found vhost config: $DOMAIN_CONF"
  echo ""
  echo "--- Current config ---"
  cat "$DOMAIN_CONF"
  echo ""
  echo "--- End of current config ---"
else
  print_warn "No existing vhost config found for $DOMAIN"
  echo "  Will create a new one."
fi

# --- 4. Back up the existing config -----------------------------------------
if [ -n "$DOMAIN_CONF" ]; then
  BACKUP="${DOMAIN_CONF}.bak.$(date +%Y%m%d%H%M%S)"
  cp "$DOMAIN_CONF" "$BACKUP"
  print_ok "Backed up to $BACKUP"
fi

# --- 5. Write the new Nginx vhost config ------------------------------------
print_step "Writing new Nginx reverse proxy config"

# Figure out where to write
if [ -n "$DOMAIN_CONF" ]; then
  TARGET="$DOMAIN_CONF"
else
  # Use the first found conf.d directory
  TARGET="${NGINX_DIRS[0]}/$DOMAIN.conf"
fi

cat > "$TARGET" <<NGINX_CONF
# ============================================================
#  Nginx reverse proxy: $DOMAIN → Node.js app on port 3000
#  Generated by fix-nginx.sh
# ============================================================

upstream nextjs_${DOMAIN//./_} {
    server 127.0.0.1:3000;
    keepalive 64;
}

server {
    listen 80;
    listen [::]:80;

    server_name $DOMAIN www.$DOMAIN;

    # Reverse proxy to Next.js on port 3000
    location / {
        proxy_pass http://nextjs_${DOMAIN//./_};
        proxy_http_version 1.1;

        # WebSocket support (needed for Next.js and chat features)
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";

        # Standard proxy headers
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;

        # Don't buffer streaming responses
        proxy_buffering off;
        proxy_cache_bypass \$http_upgrade;
    }

    # Next.js static assets — cache aggressively
    location /_next/static/ {
        proxy_pass http://nextjs_${DOMAIN//./_};
        proxy_set_header Host \$host;
        expires 365d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # Public images — cache for a week
    location /images/ {
        proxy_pass http://nextjs_${DOMAIN//./_};
        proxy_set_header Host \$host;
        expires 7d;
        add_header Cache-Control "public";
        access_log off;
    }

    location /gallery/ {
        proxy_pass http://nextjs_${DOMAIN//./_};
        proxy_set_header Host \$host;
        expires 7d;
        add_header Cache-Control "public";
        access_log off;
    }

    # Block access to hidden files and sensitive files
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    location ~* ^/(server\.js|ecosystem\.config\.js|deploy\.sh|start\.sh) {
        deny all;
    }

    # Logging
    access_log /var/log/nginx/${DOMAIN}.access.log;
    error_log /var/log/nginx/${DOMAIN}.error.log;
}
NGINX_CONF

print_ok "Wrote config to $TARGET"

# --- 6. Also check for and disable any default.conf that might catch the domain ---
print_step "Checking for conflicting default configs"

for d in "${NGINX_DIRS[@]}"; do
  for f in "$d/default" "$d/default.conf"; do
    if [ -f "$f" ] && [ "$f" != "$TARGET" ]; then
      print_warn "Found default config: $f"
      # Check if it catches the domain
      if grep -q "server_name.*_" "$f" 2>/dev/null; then
        print_warn "This default config uses server_name _ (catch-all) — it may override your domain"
        BACKUP_DEF="${f}.bak.$(date +%Y%m%d%H%M%S)"
        mv "$f" "$BACKUP_DEF"
        print_ok "Moved to $BACKUP_DEF"
      fi
    fi
  done
done

# --- 7. Also check for Webuzo's main nginx.conf that might include vhosts ---
print_step "Checking Nginx main config for vhost includes"

MAIN_CONF=""
for f in /etc/nginx/nginx.conf /usr/local/apps/nginx/etc/nginx.conf; do
  if [ -f "$f" ]; then
    MAIN_CONF="$f"
    break
  fi
done

if [ -n "$MAIN_CONF" ]; then
  print_ok "Main Nginx config: $MAIN_CONF"
  echo "  Include directives:"
  grep -n "include" "$MAIN_CONF" 2>/dev/null | head -10
fi

# --- 8. Check if the config directory is actually included by nginx ---------
if [ -n "$MAIN_CONF" ]; then
  TARGET_DIR=$(dirname "$TARGET")
  if ! grep -q "$TARGET_DIR" "$MAIN_CONF" 2>/dev/null; then
    print_warn "The directory $TARGET_DIR is NOT included in $MAIN_CONF"
    echo "  You may need to add this line to $MAIN_CONF:"
    echo "    include $TARGET_DIR/*.conf;"
  else
    print_ok "$TARGET_DIR is included in the main Nginx config"
  fi
fi

# --- 9. Test and reload Nginx -----------------------------------------------
print_step "Testing Nginx configuration"

if nginx -t 2>&1; then
  print_ok "Nginx config test passed"
  systemctl reload nginx 2>/dev/null || service nginx reload 2>/dev/null || nginx -s reload 2>/dev/null
  print_ok "Nginx reloaded"
else
  print_err "Nginx config test FAILED"
  echo "  Restoring backup..."
  if [ -n "$BACKUP" ] && [ -f "$BACKUP" ]; then
    cp "$BACKUP" "$DOMAIN_CONF"
    print_ok "Restored backup"
  fi
  exit 1
fi

# --- 10. Verify ---------------------------------------------------------------
print_step "Verifying site is accessible"

sleep 2

HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 5 "http://$DOMAIN/" 2>/dev/null || echo "000")
if echo "$HTTP_CODE" | grep -q "200\|302\|301"; then
  print_ok "Site is live at http://$DOMAIN/ (HTTP $HTTP_CODE)"
else
  print_warn "Got HTTP $HTTP_CODE from http://$DOMAIN/"
  echo "  Check: pm2 logs global-experience"
  echo "  Check: curl -v http://127.0.0.1:3000/"
fi

echo ""
echo -e "${GREEN}============================================================${NC}"
echo -e "${GREEN}  Done! $DOMAIN should now serve the Next.js app${NC}"
echo -e "${GREEN}============================================================${NC}"
echo ""
echo "If still showing default page, check:"
echo "  1. Does DNS for $DOMAIN point to this VPS IP?"
echo "  2. Is PM2 running?  → pm2 status"
echo "  3. Nginx logs: tail -f /var/log/nginx/${DOMAIN}.error.log"
echo ""
